/*
Copyright 2022 The KubeZoo Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package quota

import (
	_ "embed"
	"fmt"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/util/yaml"
)

// clusterResourceQuotaCRD is what controller-gen wrote from the Go types.
//
// ⭐ Embedded rather than transcribed. This used to be 222 lines of struct
// literals in zz.generated.crd.go, stamped "Code generated by crd-gen. DO NOT
// EDIT." -- but crd-gen is not in this repository, so nothing could regenerate
// it and DO NOT EDIT was an instruction nobody could follow. A file that looks
// maintained and is not is worse than one that is obviously missing.
//
//go:embed quota.kubezoo.io_clusterresourcequotas.yaml
var clusterResourceQuotaCRD []byte

// NewClusterResourceQuotaCRD returns the CustomResourceDefinition that makes an
// upstream cluster serve quota.kubezoo.io.
//
// ⛔ Not optional and not decorative. cmd/clusterresourcequota installs this at
// startup, and it is the only thing that does -- without it the upstream cluster
// does not serve the group, the tenant controller's discovery check returns nil,
// and no tenant quota is enforced at all.
//
// ⚠️ Panics if the embedded document does not decode. It is a compile-time
// constant produced by controller-gen, so a failure here means the build is
// broken rather than the input is bad, and returning an error would push a
// decision onto callers that none of them could make. TestCRDDecodes proves it
// decodes, so this cannot first be discovered in production.
func NewClusterResourceQuotaCRD() *apiextensionsv1.CustomResourceDefinition {
	crd, err := decodeClusterResourceQuotaCRD()
	if err != nil {
		panic(fmt.Sprintf("the embedded ClusterResourceQuota CRD does not decode, "+
			"which means this binary was built from a broken tree: %v", err))
	}
	return crd
}

func decodeClusterResourceQuotaCRD() (*apiextensionsv1.CustomResourceDefinition, error) {
	crd := &apiextensionsv1.CustomResourceDefinition{}
	if err := yaml.UnmarshalStrict(clusterResourceQuotaCRD, crd); err != nil {
		return nil, err
	}
	return crd, nil
}
